spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;INIT=SET NAMES UTF8
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
      defer-datasource-initialization: true
      properties:
        hibernate.show_sql: true
        hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
